version: '3.7'

services:

  app:
    build: .
    volumes:
      - .:/app
      - home-server-dev-deps-volume:/app/deps
      - home-server-dev-build-volume:/app/_build
      - home-server-dev-node-modules-volume:/app/assets/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres
    volumes:
      - home-server-dev-db-volume:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=example"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
  home-server-dev-deps-volume:
  home-server-dev-build-volume:
  home-server-dev-node-modules-volume:
  home-server-dev-db-volume:
