FROM elixir:1.10 AS build

# install build dependencies
RUN apt-get update && apt-get install -y \
      build-essential \
      nodejs \
      npm

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# set build ENV
ENV MIX_ENV=prod

# install mix dependencies
COPY mix.exs mix.lock ./
COPY config config
RUN mix do deps.get, deps.compile

# build assets
COPY assets/package.json assets/package-lock.json ./assets/
RUN npm --prefix ./assets install

COPY priv priv
COPY assets assets
RUN npm run --prefix ./assets deploy
RUN mix phx.digest

# compile and build release
COPY lib lib
# uncomment COPY if rel/ exists
# COPY rel rel
RUN mix do compile, release

# prepare release image
FROM debian:buster AS app

RUN groupadd -g 1500 app \
  && useradd --create-home -u 1500 -g app app

RUN mkdir -p /app \
 && chown -R app:app /app

WORKDIR /app
USER app:app

COPY --from=build --chown=app:app /app/_build/prod/rel/home_server ./

ENV HOME=/app

CMD ["bin/home_server", "start"]
