version: '3.7'

services:

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_PASSWORD=example"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
