version: '3.7'

services:

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - "DATABASE_URL=ecto://postgres:example@db/home_server_dev"
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=example"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
